config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users
  root to: "inflatables#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :inflatables do
    resources :bookings, only: %i[new create]
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
  resources :bookings, only: %i[show destroy update]



  get 'home', to: 'inflatables#index'
  get 'dashboard', to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :inflatable
  validates :start_date, presence: true
  validates :end_date, presence: true

  def pending?
    status == nil
  end
end

app/models/inflatable.rb
class Inflatable < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :bookings
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  validates :description, length: { minimum: 6 }
  validates :price, presence: true
  validates :category, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :inflatable

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :inflatables, dependent: :destroy
  has_many :bookings, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_inflatable, only: %i[new create]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.inflatable = @inflatable
    @booking.user = current_user
    total_days = (@booking.end_date - @booking.start_date).to_i + 1
    @booking.total_price = @inflatable.price * total_days
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
      # render # where was the booking update form?
    end
  end


  # def show
  #   @booking = Booking.find(params[:id])
  # end

  # def destroy
  #   @booking = Booking.find(params[:id])
  #   @booking.destroy
  #   redirect_to inflatable_path(@booking.inflatable), status: :see_other
  # end

  private

  def set_inflatable
    @inflatable = Inflatable.find(params[:inflatable_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/inflatables_controller.rb
class InflatablesController < ApplicationController
  before_action :set_inflatable, only: [:show, :edit, :update, :destroy]
  def index
    @inflatables = Inflatable.all
  end

  def show
    @booking = Booking.new
    # suggestions variable
    # where you get category of inflatable
    # limit 4
    # active records query
    # exclude from search the one already shown
    # @inflatables = Inflatable.where(category: @inflatable.category).limit(4).offset(1)
    @inflatables = Inflatable.where(category: @inflatable.category).where.not(id: @inflatable.id).limit(4)
  end

  def new
    @inflatable = Inflatable.new
  end

  def create
    @inflatable = Inflatable.new(inflatable_params)
    @inflatable.user = current_user
    if @inflatable.save
      redirect_to inflatables_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @inflatable.update(inflatable_params)
      redirect_to inflatables_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @inflatable.destroy
    redirect_to inflatables_path, status: :see_other
  end

  private

  def inflatable_params
    params.require(:inflatable).permit(:title, :description, :category, :price, :photo)
  end

  def set_inflatable
    @inflatable = Inflatable.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: %i[dashboard]
  def home
  end

  def dashboard
    @inflatables = Inflatable.where(user: current_user)
    @my_bookings = Booking.where(user: current_user)
    @bookings_for_my_inflatables = Booking.where(inflatable: @inflatables)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_inflatable, only: %i[new create]
  def new
    @inflatable = Inflatable.find(params[:inflatable_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.inflatable = @inflatable
    if @review.save
      redirect_to inflatable_path(@inflatable)
    else
      render "inflatables/show", status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to inflatable_path(@review.inflatable), status: :see_other
  end

  private

  def set_inflatable
    @inflatable = Inflatable.find(params[:inflatable_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def method_name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<p>Should display something like summary of the reservation</p>
<p> price</p>
<p>dates</p>
<p>total days</p>
<p>if we are not log, need to sign in, etc</p>

app/views/inflatables/_form.html.erb
<%= simple_form_for(inflatable) do |f| %>
  <!-- [...] -->
  <%= f.input :photo, as: :file %>
  <!-- [...] -->
<% end %>

app/views/inflatables/index.html.erb
  <h2>All inflatables</h2>
  <div class="row row-cols-12 row-cols-md-4 g-4">
      <% @inflatables.each do |inflatable| %>
        <%# <div class="col"> %>
          <div class="card-group">
            <div class="card h-100 card-style" style="width: 18rem;">
              <%# <div><i class="fa-regular fa-heart"></i></div> %>
              <%= link_to inflatable_path(inflatable) do %>
              <%# <img src="https://source.unsplash.com/random/400×300/?ballon" class="card-img-top inflatable" alt="..."> %>
                <div class="inflatable" >
                  <%= cl_image_tag(inflatable.photo.key, class: "card-img-top inflatable-img") if inflatable.photo.key %>
                </div>
              <div class="card-body">
                <h6 class="card-subtitle "><%= inflatable.category %></h6>
                <p class="card-title"><%= inflatable.title %></p>
                <div class="price-label text-center align-middle">
                  <h3 class="card-price">€ <%= inflatable.price %></h3>
                </div>
              </div>
            <% end %>
            </div>
          </div>
        <%# </div> %>
      <% end %>
  </div>

app/views/inflatables/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-6">
      <div class="containerd-flex justify-content-center">
          <h2>Share your inflatable</h2>
          <%= simple_form_for @inflatable do |f| %>
            <div class="form-inputs">
              <%= f.input :title %>
              <%= f.input :description %>
              <%= f.input :category, collection: ["toys", "costumes", "slides", "balloons", "pools"]%>
              <%= f.input :price %>
              <%= f.input :photo, as: :file%>
            </div>
              <div class="form-actions">
                <%= f.button :submit, class: "btn btn-primary" %>
              </div>
          <% end %>
      </div>
    </div>
    <div class="col-6">
      <img src="https://images.unsplash.com/photo-1501426026826-31c667bdf23d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2836&q=80"
          alt="Login image" class="w-100 vh-100" style="object-fit: cover; object-position: left;">
    </div>
  </div>
</div>

app/views/inflatables/show.html.erb
<!-- Page Content -->
<section class="py-5 bg-white">
  <div class="container px-4 px-lg-5 my-5">
      <div class="row gx-4 gx-lg-5">
          <div class="col-md-6"><%= cl_image_tag(@inflatable.photo.key, width: 500, crop: :fill) if @inflatable.photo.key %></div>
          <div class="col-md-6">
              <div class="small mb-1"><%= @inflatable.category.upcase %></div>
              <h1 class="display-5 fw-bolder"><%= @inflatable.title %></h1>
              <div class="fs-5 mb-5">
                <span style="background-color: black; color: white; border-radius: 15px; padding: 3px 10px"><%= @inflatable.price %>€</span>
              </div>
              <p class="lead"><%= @inflatable.description %></p>
              <div class="d-flex">
              <!-- Dates for the reservation -->
              <%= simple_form_for [@inflatable, @booking], data: { controller: 'flatpickr' }, html: {class: "w-100"}  do |f| %>
                <div class="d-flex w-100">
                  <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startTime" } }, wrapper_html: { class: "flex-grow-1" } %>
                  <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endTime" }, id: 'end_time' }, wrapper_html: { class: "flex-grow-1" } %>
                </div>
                  <%= f.submit :class => "btn btn-primary" %>
              <% end %>
          </div>
      </div>
    </div>
  </div>
</section>

<section class="py-5 bg-light" style="margin-top: 50px">
  <div class="container px-4 px-lg-5 mt-5"> <h1>Check what other users have to say: </h1>
      <% @inflatable.reviews.each do |review| %>
        <div class="card mb-4">
          <div class="card-body">
          <p><%= review.content %></p>
          </div>
        </div>
      <% end %>
        <%= link_to "Write a review",
              new_inflatable_review_path(@inflatable),
            :class => "btn btn-dark btn-lg btn-block"
          %>
      </div>
</section>

<!-- further recommendations-->
<section class="py-5 bg-light" style="margin-top: 50px">
  <div class="container px-4 px-lg-5 mt-5 fw-bolder"> <h1>You might also be interested in: </h1>
      <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        <% @inflatables.each do |inflatable| %>
          <div class="card-group">
            <div class="card h-100 card-style" style="width: 18rem;">
              <%= link_to inflatable_path(inflatable) do %>
              <%= cl_image_tag(inflatable.photo.key, class: "card-img-top inflatable") if inflatable.photo.key %>
              <div class="card-body">
                <h6 class="card-subtitle "><%= inflatable.category %></h6>
                <p class="card-title"><%= inflatable.title %></p>
                <div class="price-label text-center align-middle">
                  <h3 class="card-price">€ <%= inflatable.price %></h3>
                </div>
              </div>
            <% end %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InflatablesAppMarketplace</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="page-container">
      <div class="navbar-container"><%= render "shared/navbar" %></div>
      <div class="content-container container"><%= yield %></div>
      <div class="footer-container"><%= render "shared/footer" %></div>
    </div>

  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>My Dashboard</h1>

  <% if @my_bookings.count >= 0 %> <h2>My Bookings</h2> <% end %>
  <div class="row g-4">
      <% @my_bookings.each do |booking| %>
      <div class="col-12 col-sm-6 col-md-3">
      <div class="card-group">
        <div class="card h-100 card-style">
            <div class="inflatable">
              <%= cl_image_tag(booking.inflatable.photo.key, class: "card-img-top inflatable-img") if booking.inflatable.photo.key %>
            </div>
          <div class="card-body">
            <h6 class="card-subtitle "><%= booking.inflatable.category %></h6>
            <p class="card-title"><%= booking.inflatable.title %></p>
            <p class="card-label">Timescale</p>
            <p class="card-date"><%= booking.start_date %> - <%= booking.end_date %></p>
            <p class="booking-tag-user booking-tag-<%= booking.status.nil? ? "pending": booking.status.downcase %>"><%= booking.status.nil? ? "Pending": booking.status.downcase  %></p>

            <div class="price-label text-center align-middle">
                  <h3 class="card-price">€ <%= booking.total_price %></h3>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="row">
    <div class="d-flex justify-content-between  mt-4 mb-4">
      <h2 class= "m-0">My inflatables</h2>
      <%= link_to "Add offer", new_inflatable_path, class:"btn btn-primary" %>
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
      <% @inflatables.each do |inflatable| %>
      <div class="col-12 col-sm-6 col-md-3">
        <div class="card-group">
          <div class="card h-100 card-style">
            <div class="inflatable">
                <%= cl_image_tag(inflatable.photo.key, class: "card-img-top inflatable-img") if inflatable.photo.key %>
            </div>
            <div class="card-body">
              <h6 class="card-subtitle "><%= inflatable.category %></h6>
              <h2 class="card-title"><%= inflatable.title %></h2>

              <%# <p class="card-text"><%= inflatable.description</p> %>
              <div class="price-label text-center align-middle">
                  <h3 class="card-price">€ <%= inflatable.price %></h3>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
  </div>

  <div class="row">
    <div class="d-flex justify-content-between mt-4">
      <h2 class= "m-0">Booking requests</h2>
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
      <% @bookings_for_my_inflatables.each do |booking| %>
      <div class="col-12 col-sm-6 col-md-3">
        <div class="card-group">
          <div class="card h-100 card-style">
            <div class="inflatable">
                <%= cl_image_tag(booking.inflatable.photo.key, class: "card-img-top inflatable-img") if booking.inflatable.photo.key %>
            </div>
            <div class="card-body">
              <h6 class="card-subtitle "><%= booking.inflatable.category %></h6>
              <h2 class="card-title"><%= booking.inflatable.title %></h2>
              <%# <p class="card-text"><%= inflatable.description</p> %>
              <div class="price-label text-center align-middle">
                  <h3 class="card-price">€ <%= booking.inflatable.price %></h3>
              </div>
              <%# <%= render "shared/booking_accept" %>
              <%# Do i need to pass any variable in this render? (as alex did in the lecture)%>
            </div>
            <div class="d-flex gap-2 booking-tag">
              <% if booking.pending? %>
                <div>
                  <%= simple_form_for booking do |f| %>
                    <%= f.input :status, as: :hidden, input_html: { value: 'Accepted'} %>
                    <%= f.submit 'Accept', class: 'btn btn-success' %>
                  <% end %>
                </div>
                <div class="me-3">
                  <%= simple_form_for booking do |f| %>
                    <%= f.input :status, as: :hidden, input_html: { value: 'Rejected'} %>
                    <%= f.submit 'Reject', class: 'btn btn-light' %>
                  <% end %>
                </div>
              <% else %>
                <p class="booking-tag booking-tag-<%= booking.status.downcase %>"><%= booking.status %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
  </div>

app/views/pages/home.html.erb
<%# <h1>Landing Page</h1> %>

<div id="myMenu">
  <div class="FrontPageLogo">
    <nav>
    <a href="/inflatables"><img src="https://vignette.wikia.nocookie.net/disney/images/7/71/Rex_1.png/revision/latest?cb=20160531222519" height="300"/></a>
    </nav>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@inflatable, @review] do |f| %>

  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-dark btn-lg btn-block" %>
  <%= link_to "Back",
                inflatable_path(@inflatable),
            :class => "btn btn-dark btn-lg btn-block"
          %>
<% end %>

app/views/shared/_booking_accept.html.erb
<p class="card-lable">Status</p>
<div class="bookings">
  <% @bookings_for_my_inflatables.each do |booking| %>
    <div class="booking">
      <div class='booking-left'>
        <!-- if you're using cloudinary and activestorage -->
        <%# <%= cl_image_tag booking.user.photo, class: 'avatar-bordered' %>
        <div class="booking-info">
          <div class="booking-info-title">
            <%= booking.user.first_name %>
          </div>
          <div class="booking-info-details">
           <%# <%= booking.start_time.strftime('%l:%M %p') - <%= booking.end_time.strftime('%l:%M %p') %>
          </div>
        </div>
      </div>
      <div class="booking-actions">
        <% if booking.pending? %>
          <div>
            <%= simple_form_for booking do |f| %>
              <%= f.input :status, as: :hidden, input_html: { value: 'Accepted'} %>
              <%= f.submit 'Accept', class: 'btn btn-success mr-4' %>
            <% end %>
          </div>
          <div>
            <%= simple_form_for booking do |f| %>
              <%= f.input :status, as: :hidden, input_html: { value: 'Rejected'} %>
              <%= f.submit 'Reject', class: 'btn btn-light' %>
            <% end %>
          </div>
        <% else %>
          <p class="booking-tag"><%= booking.status %></p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer mt-5">
  <div class="footer-links">
    <a href="https://www.instagram.com/explore/tags/inflatables/"><i class="fab fa-instagram"></i> Follow us</a>
    <a href="https://www.facebook.com/inflatabledeals/"><i class="fab fa-facebook"></i> Like us</a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by balloon animals.
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark fixed-top" data-bs-theme="dark">
  <div class="container">
    <%= link_to 'INFLATABROS', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex">
        <%# <li class="nav-item">
          <%= link_to 'Inflatables', inflatables_path, class:"nav-link active text-white" %>
        <%# </li> %> 
      </ul>
    </div>
    <% if user_signed_in? %>
      <div class="nav-item dropdown">
          <%= image_tag "https://p6.focus.de/img/fotos/id_561486/herschel-krustofski-pascal.gif?im=Resize%3D%28630%2C630%29&impolicy=perceptual&quality=medium&hash=239d6d997d1af9526b517020b5de56bd8adb364d2e3c82f19aba32646d202895", class: "avatar dropdown-toggle ", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
      </div>
    <% else %>
      <div class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </div>
    </div>
    <% end %>
</nav>